name: HomeClaw
options:
  bundleIdPrefix: com.shahine
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    DEAD_CODE_STRIPPING: YES
    SWIFT_EMIT_LOC_STRINGS: YES
    CODE_SIGN_STYLE: Automatic

packages:
  swift-argument-parser:
    url: https://github.com/apple/swift-argument-parser.git
    from: "1.7.0"

targets:
  # ─── Unified Catalyst App ─────────────────────────────────
  HomeClaw:
    type: application
    platform: iOS
    attributes:
      UIKitCatalyst: optimized
    sources:
      - path: Sources/homeclaw
        excludes:
          - "**/_disabled/**"
      - path: Resources/HomeClaw.icns
        buildPhase: resources
      - path: Resources/HomeClaw.icon
        buildPhase: resources
      - path: Resources/PrivacyInfo.xcprivacy
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shahine.homeclaw
        PRODUCT_NAME: HomeClaw
        TARGETED_DEVICE_FAMILY: "6"
        SUPPORTS_MACCATALYST: YES
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/HomeClaw.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: HomeClaw
        MACOSX_BUNDLE_ICON_FILE: HomeClaw
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_USER_SCRIPT_SANDBOXING: NO
      configs:
        Debug:
          ENABLE_APP_SANDBOX: NO
        Release:
          ENABLE_APP_SANDBOX: YES
          ENABLE_INCOMING_NETWORK_CONNECTIONS: YES
          ENABLE_OUTGOING_NETWORK_CONNECTIONS: YES
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited) APP_STORE"
    entitlements:
      path: Resources/HomeClaw.entitlements
      properties:
        com.apple.developer.homekit: true
        com.apple.security.application-groups:
          - group.com.shahine.homeclaw
    dependencies:
      - target: macOSBridge
        platformFilter: maccatalyst
      - target: homeclaw-cli
        embed: false
      - sdk: HomeKit.framework
    preBuildScripts:
      - name: "Increment Build Number (Archive Only)"
        script: |
          # Only bump during Release builds (i.e. archive), not Debug
          if [ "$CONFIGURATION" != "Release" ]; then
            exit 0
          fi

          BUILD_NUMBER_FILE="${PROJECT_DIR}/.build-number"
          PLIST="${PROJECT_DIR}/Resources/Info.plist"

          if [ -f "$BUILD_NUMBER_FILE" ]; then
            BUILD_NUMBER=$(( $(cat "$BUILD_NUMBER_FILE") + 1 ))
          else
            BUILD_NUMBER=$(git -C "${PROJECT_DIR}" rev-list --count HEAD 2>/dev/null || echo "1")
          fi

          echo "$BUILD_NUMBER" > "$BUILD_NUMBER_FILE"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$PLIST"
          echo "Build number set to $BUILD_NUMBER"
        basedOnDependencyAnalysis: false
      - name: "Build MCP Server"
        script: |
          if command -v node &>/dev/null && [ -f "${PROJECT_DIR}/mcp-server/build.mjs" ]; then
            cd "${PROJECT_DIR}"
            if [ ! -f "mcp-server/dist/server.js" ] || [ "mcp-server/server.js" -nt "mcp-server/dist/server.js" ]; then
              node mcp-server/build.mjs 2>/dev/null || echo "warning: MCP server build skipped"
            fi
          fi
        basedOnDependencyAnalysis: false
    postBuildScripts:
      - name: "Bundle CLI + Resources"
        script: |
          APP="${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Contents"

          # Copy homeclaw-cli into Contents/MacOS/
          # CLI is a native macOS tool — look in the macOS build dir (Debug/),
          # not the Catalyst dir (Debug-maccatalyst/)
          CLI_PATH="${BUILD_DIR}/${CONFIGURATION}/homeclaw-cli"
          if [ -f "${CLI_PATH}" ]; then
            cp "${CLI_PATH}" "${APP}/MacOS/homeclaw-cli"
          elif [ -f "${BUILT_PRODUCTS_DIR}/homeclaw-cli" ]; then
            cp "${BUILT_PRODUCTS_DIR}/homeclaw-cli" "${APP}/MacOS/homeclaw-cli"
          fi

          # Copy mcp-server.js into Contents/Resources/
          MCP_JS="${PROJECT_DIR}/mcp-server/dist/server.js"
          if [ -f "${MCP_JS}" ]; then
            cp "${MCP_JS}" "${APP}/Resources/mcp-server.js"
          fi

          # Copy openclaw plugin files into Contents/Resources/openclaw/
          OPENCLAW="${PROJECT_DIR}/openclaw"
          if [ -d "${OPENCLAW}" ]; then
            DEST="${APP}/Resources/openclaw"
            mkdir -p "${DEST}"
            cp "${OPENCLAW}/openclaw.plugin.json" "${DEST}/"
            cp "${OPENCLAW}/package.json" "${DEST}/"
            cp -R "${OPENCLAW}/src" "${DEST}/src"
            cp -R "${OPENCLAW}/skills" "${DEST}/skills"
          fi
        basedOnDependencyAnalysis: false

  # ─── macOS Bridge Bundle (AppKit menu bar) ─────────────────
  macOSBridge:
    type: bundle
    platform: macOS
    sources:
      - path: Sources/macOSBridge
      - path: Sources/homeclaw/Bridge
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shahine.homeclaw.macOSBridge
        PRODUCT_NAME: macOSBridge
        INFOPLIST_FILE: Sources/macOSBridge/Info.plist
        SKIP_INSTALL: YES
        MACOSX_DEPLOYMENT_TARGET: "15.0"

  # ─── CLI Tool ──────────────────────────────────────────────
  homeclaw-cli:
    type: tool
    platform: macOS
    sources:
      - path: Sources/homeclaw-cli
        excludes:
          - "**/Commands/_disabled/**"
    dependencies:
      - package: swift-argument-parser
        product: ArgumentParser
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shahine.homeclaw.cli
        PRODUCT_NAME: homeclaw-cli
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Resources/homeclaw-cli.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        SKIP_INSTALL: YES
        CREATE_INFOPLIST_SECTION_IN_BINARY: YES
        GENERATE_INFOPLIST_FILE: YES
      configs:
        Debug:
          ENABLE_APP_SANDBOX: NO
        Release:
          ENABLE_APP_SANDBOX: YES
          ENABLE_OUTGOING_NETWORK_CONNECTIONS: YES

schemes:
  HomeClaw:
    build:
      targets:
        HomeClaw: all
        macOSBridge: all
        homeclaw-cli: all
    run:
      config: Debug
      executable: HomeClaw
    archive:
      config: Release
    profile:
      config: Release
