name: HomeClawHelper
options:
  bundleIdPrefix: com.shahine
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.4"
settings:
  SUPPORTS_MACCATALYST: "YES"
  DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: "NO"
  SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
  SWIFT_VERSION: "6.0"
targets:
  HomeClawHelper:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.xcodeproj"
          - "*.entitlements"
      - path: ../../Resources/HomeClaw.icon
        buildPhase: resources
      - path: ../../Resources/HomeClaw.icns
        buildPhase: resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.shahine.homeclaw.helper
      INFOPLIST_FILE: Info.plist
      CODE_SIGN_ENTITLEMENTS: HomeClawHelper.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: YOUR_TEAM_ID
      SUPPORTS_MACCATALYST: "YES"
      DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: "NO"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
      TARGETED_DEVICE_FAMILY: "2"
      SWIFT_STRICT_CONCURRENCY: complete
      ASSETCATALOG_COMPILER_APPICON_NAME: HomeClaw
      MACOSX_BUNDLE_ICON_FILE: HomeClaw
    entitlements:
      path: HomeClawHelper.entitlements
      properties:
        com.apple.developer.homekit: true
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.com.shahine.homeclaw
        com.apple.security.network.server: true
